---
# ================== CLUSTER ROLE ==================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # Défintit des droits spécifiques, associés au compte précédement crée, afin que les pods puisses posséder des droits necessaire  à leur fonctionnement
metadata:
  name: {{ .Release.Name }}-prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]