---
# ================== NodeExporter pour les metric systèmes ==================
apiVersion: apps/v1
kind: DaemonSet # Ces pods seront présents sur tous les noeuds du cluster. Cela permet de remonter des stats système pour chacun des noeuds
# Contrairement aux deployments qui peuvent avoir plusieurs instances sur le même noeud, le deamonSet ne possède qu'une instance par noeud, le strict nécessaire dans notre cas
metadata:
  name: node-exporter
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
    spec:
      hostNetwork: true
      containers:
        - name: node-exporter
          image: {{ .Values.node_exporter.image }} # Image du nodeExporter prometheus: [https://github.com/prometheus/node_exporter]
          ports:
            - containerPort: 9100