---
# ================== SERVICE ACCOUNT ==================
apiVersion: v1
kind: ServiceAccount # Un Service qui sera utilisé par tous les pods prometheus
metadata:
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Values.namespace.name }}