{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.mysql.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.password | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  selector:
    app: {{ .Release.Name }}-mysql
  ports:
    - port: 3306
  {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-symfony
spec:
  replicas: {{ .Values.symfony.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-symfony
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-symfony
    spec:
      containers:
        - name: symfony
          image: {{ .Values.symfony.image }}
          env:
            - name: DATABASE_URL
              value: "mysql://root:{{ .Values.mysql.password }}@{{ .Release.Name }}-mysql:3306/{{ .Values.mysql.database }}"

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-symfony
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-symfony
  ports:
    - port: 80
      targetPort: 80