{{/* Déploiement MYSQL */}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db-name
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-pvc
---

---
{{/* Déploiement Symfony */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-symfony
spec:
  replicas: {{ .Values.symfony.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-symfony
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-symfony
    spec:
      containers:
        - name: symfony
          image: {{ .Values.symfony.image }}
          env:
            - name: DATABASE_URL
              value: "mysql://root:{{ .Values.mysql.password }}@{{ .Release.Name }}-mysql:3306/{{ .Values.mysql.database }}"