---
# -------------------- SECRETS --------------------
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  app-secret: {{ .Values.secrets.appSecret | b64enc | quote }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
  db-user: {{ .Values.secrets.dbUser | b64enc | quote }}
  db-name: {{ .Values.secrets.dbName | b64enc | quote }}
  # Construction de l'URL
  database-url: {{ printf "mysql://%s:%s@%s-mysql:3306/%s" .Values.secrets.dbUser .Values.secrets.dbPassword .Release.Name .Values.secrets.dbName | b64enc | quote }}