
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/"
spec:
  type: NodePort
  selector:
    app: {{ .Realese.name }}-nginx
  ports:
    - protocol: TCP
      port: {{ nginx.service.external_port }}
      targetPort: {{ nginx.service.internal_port }}
