{{/* Déploiement MYSQL */}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrations-job
  annotations:
    argocd.argoproj.io/sync-options: Delete=true
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-migrations-job
    spec:
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
      {{- end }}
      restartPolicy: OnFailure
      initContainers:
        # Attendre que MySQL soit prêt
        - name: wait-for-mysql
          image: busybox:1.35
          {{- if .Values.securityContext_pod }}
          securityContext:
             {{- toYaml .Values.securityContext_pod | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL to be ready..."
              until nc -z {{ .Release.Name }}-mysql {{ .Values.mysql.port }}; do
                echo "MySQL is not ready yet, waiting 5 seconds..."
                sleep 5
              done
              echo "MySQL is ready!"

---
{{/* Déploiement Symfony */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-symfony
spec:
  replicas: {{ .Values.symfony.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-symfony
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-symfony
    spec:
    {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
    {{- end }}
      containers:
        - name: symfony
          {{- if .Values.securityContext_pod }}
          securityContext:
             {{- toYaml .Values.securityContext_pod | nindent 12 }}
          {{- end }}
          image: {{ .Values.symfony.image }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: database-url
          {{- if $.Values.resources }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
           {{- end }}
          livenessProbe:
            httpGet:
              path: /article
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /article
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3