---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrations-job
  annotations:
    argocd.argoproj.io/sync-options: Delete=true
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-migrations-job
    spec:
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
      {{- end }}
      restartPolicy: OnFailure
      initContainers:
        # Attendre que MySQL soit prêt
        - name: wait-for-mysql
          image: bitnami/mysql:latest
          {{- if .Values.securityContext_pod }}
          securityContext:
             {{- toYaml .Values.securityContext_pod | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - |
              until mysqladmin ping -h {{ .Release.Name }}-mysql -u $MYSQL_USER -p$MYSQL_PASSWORD --silent; do
                echo "Waiting for MySQL..."
                sleep 2
              done
              echo "MySQL is ready!"
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db-user

      containers:
        - name: symfony-migrations
          image: {{ .Values.symfony.image }}
          {{- if .Values.securityContext_pod }}
          securityContext:
             {{- toYaml .Values.securityContext_pod | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - |
              echo "Starting Symfony migrations..."
              echo "Database URL: $DATABASE_URL"
              php bin/console doctrine:database:create --if-not-exists
              php bin/console doctrine:migrations:migrate --no-interaction
              echo "Migrations completed successfully!"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: database-url
            - name: APP_ENV
              value: "prod"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: app-secret
          workingDir: /var/www/html