---
# -------------------- SECRETS --------------------
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  app-secret: {{ .Values.secrets.appSecret | quote }}
  db-password: {{ .Values.secrets.databasePassword | quote }}
  db-user: {{ .Values.secrets.databaseUsername | quote }}
  db-name: {{ .Values.secrets.databaseName | quote }}
  # Construction de l'URL avec stringData pour éviter les problèmes d'encodage
  database-url: {{ printf "mysql://%s:%s@%s-mysql:3306/%s" .Values.secrets.databaseUsername .Values.secrets.databasePassword .Release.Name .Values.secrets.databaseName | quote }}