# -------------------- DÉPLOIEMENT Nginx --------------------
apiVersion: apps/v1                 # Version de l'API Kubernetes utilisée pour les déploiements (apps/v1 est la version stable actuelle).
kind: Deployment                    # Type de ressource : un Deployment, qui gère la création, la mise à l'échelle et les mises à jour des Pods.
metadata:
  name: nginx-clusterip-test        # Nom du Deployment. Sert d'identifiant unique dans le namespace.

spec:                               # Section spécifiant la configuration du Deployment.
  replicas: 2                       # Nombre de Pods répliqués que l'on souhaite (ici, 2 Pods Nginx identiques tourneront en parallèle).

  selector:                         # Définit quels Pods seront gérés par ce Deployment.
    matchLabels:                    # Condition : les Pods doivent avoir les labels spécifiés ci-dessous.
      app: nginx-clusterip          # Ici, tous les Pods avec le label "app: nginx-clusterip" seront gérés par ce Deployment.

  template:                         # Modèle de Pod à utiliser pour créer les réplicas.
    metadata:
      labels:                       # Labels appliqués aux Pods créés par ce Deployment.
        app: nginx-clusterip        # Ce label doit correspondre au "selector" plus haut pour que le Service et le Deployment fonctionnent correctement.

    spec:                           # Spécification du Pod (contenu du Pod).
      containers:                   # Liste des containers qui tourneront dans chaque Pod.
        - name: nginx               # Nom interne du container dans le Pod.
          image: nginx:alpine       # Image Docker utilisée. 'nginx:alpine' est une version légère de Nginx basée sur Alpine Linux.
          ports:                    # Définition des ports exposés par le container.
            - containerPort: 80     # Le container écoute sur le port 80 (port HTTP par défaut).

---
# -------------------- SERVICE CLUSTERIP --------------------
apiVersion: v1                     # Version de l'API Kubernetes utilisée pour les services (v1 est la version stable).
kind: Service                      # Type de ressource : un Service, qui expose les Pods et permet la communication réseau.
metadata:
  name: nginx-clusterip-service    # Nom du Service. Servira de nom DNS interne pour accéder à Nginx depuis d'autres Pods du cluster.

spec:                              # Section spécifiant la configuration du Service.
  type: ClusterIP                  # Type de Service : ClusterIP rend le service accessible uniquement depuis l'intérieur du cluster Kubernetes.
  # C'est le type par défaut - il crée une IP virtuelle interne stable.

  selector:                        # Définit quels Pods seront exposés par ce Service.
    app: nginx-clusterip           # Tous les Pods avec le label "app: nginx-clusterip" seront inclus dans ce Service (correspond au Deployment).

  ports:                           # Configuration des ports du Service.
    - protocol: TCP                # Protocole utilisé (TCP est le plus courant pour HTTP).
      port: 80                     # Port sur lequel le Service écoute (port accessible par les autres Pods du cluster).
      targetPort: 80               # Port du container vers lequel le trafic sera redirigé (doit correspondre au containerPort du Deployment).
