# -------------------- CONFIGMAP POUR POD 1 --------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-pod1
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Load Balancing Demo - Pod 1</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                text-align: center;
                padding: 50px;
                margin: 0;
            }
            .container {
                background: rgba(255,255,255,0.1);
                border-radius: 20px;
                padding: 40px;
                max-width: 600px;
                margin: 0 auto;
                backdrop-filter: blur(10px);
            }
            h1 { font-size: 2.5em; margin-bottom: 20px; }
            .pod-info {
                background: rgba(255,255,255,0.2);
                padding: 20px;
                border-radius: 10px;
                margin: 20px 0;
            }
            .timestamp {
                font-size: 1.2em;
                color: #ffeb3b;
                margin-top: 20px;
            }
        </style>
    </head>
    <body>
    <div class="container">
        <h1>🚀 KUBERNETES LOAD BALANCER</h1>
        <div class="pod-info">
            <h2>📦 POD N°1 - BLEU</h2>
            <p><strong>Serveur:</strong> nginx-pod-1</p>
            <p><strong>Couleur:</strong> Bleu / Violet</p>
        </div>
        <p>Rechargez cette page (F5) pour voir le load balancing en action !</p>
        <div class="timestamp">
            ⏰ Chargé le : <span id="time"></span>
        </div>
    </div>
    <script>
        document.getElementById('time').textContent = new Date().toLocaleString('fr-FR');
    </script>
    </body>
    </html>

---
# -------------------- CONFIGMAP POUR POD 2 --------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-pod2
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Load Balancing Demo - Pod 2</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
                color: white;
                text-align: center;
                padding: 50px;
                margin: 0;
            }
            .container {
                background: rgba(255,255,255,0.1);
                border-radius: 20px;
                padding: 40px;
                max-width: 600px;
                margin: 0 auto;
                backdrop-filter: blur(10px);
            }
            h1 { font-size: 2.5em; margin-bottom: 20px; }
            .pod-info {
                background: rgba(255,255,255,0.2);
                padding: 20px;
                border-radius: 10px;
                margin: 20px 0;
            }
            .timestamp {
                font-size: 1.2em;
                color: #ffeb3b;
                margin-top: 20px;
            }
        </style>
    </head>
    <body>
    <div class="container">
        <h1>🚀 KUBERNETES LOAD BALANCER</h1>
        <div class="pod-info">
            <h2>📦 POD N°2 - ROSE</h2>
            <p><strong>Serveur:</strong> nginx-pod-2</p>
            <p><strong>Couleur:</strong> Rose / Rouge</p>
        </div>
        <p>Rechargez cette page (F5) pour voir le load balancing en action !</p>
        <div class="timestamp">
            ⏰ Chargé le : <span id="time"></span>
        </div>
    </div>
    <script>
        document.getElementById('time').textContent = new Date().toLocaleString('fr-FR');
    </script>
    </body>
    </html>

---
# -------------------- DÉPLOIEMENT POD 1 --------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-nodeport
      pod: pod1
  template:
    metadata:
      labels:
        app: nginx-nodeport
        pod: pod1
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: nginx-html-pod1

---
# -------------------- DÉPLOIEMENT POD 2 --------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-nodeport
      pod: pod2
  template:
    metadata:
      labels:
        app: nginx-nodeport
        pod: pod2
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: nginx-html-pod2

---
# -------------------- SERVICE NODEPORT --------------------
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx-nodeport  # Sélectionne TOUS les pods avec ce label (pod1 ET pod2)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#      nodePort: 30080  # Port fixe pour faciliter les tests