postgresql:
  image: "postgres:15"
  replica: 2
  service:
    external_port: 5432
    internal_port: 5432
  pvc:
    size: "1Gi"
secrets:
  postgres_user: "postgre_user"
  postgres_password: "postgres_password"
  postgres_db: "postgres_db"
