baseURL = 'http://localhost:1313'
title = 'K3s Deployment Samples'
languageCode = 'fr-FR'

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
name = "Basics"
url = "/basics/"
weight = 10

[[menu.main]]
name = "GitHub"
url = "https://github.com/maxime67/manifest_k3s_sample"
weight = 20
