---
# -------------------- SERVICE NodePort --------------------
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-react-test-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-react
  ports:
    - protocol: TCP
      port: {{ .Values.react.service.external_port }}
      targetPort: {{ .Values.react.service.internal_port }}